const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Revolver CO2, Crossman, 6 tiros",
      price: 10455,
      image: require('../images/img01.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 5,
    },    
    {
      id: 2,
      title: "Pistola CO2, Umarex, 18 tiros",
      price: 9450,
      image: require('../images/img02.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 3,
    },     
    {
      id: 3,
      title: "Pistola CO2, Daisy, 21 tiros",
      price: 11400,
      image: require('../images/img03.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 1,
    }, 
    {
      id: 4,
      title: "Pistola CO2, GAMO, 20 tiros",
      price: 12400,
      image: require('../images/img04.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 2,
    },
    {
      id: 5,
      title: "Pistola CO2, Swiss Arms, 18 tiros",
      price: 9400,
      image: require('../images/img05.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 7,
    },
    {
      id: 6,
      title: "Pistola CO2, Stinger, 20 tiros",
      price: 10400,
      image: require('../images/img06.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 4,
    },
    {
      id: 7,
      title: "Pistola CO2, Swiss Arms, 18 tiros",
      price: 14500,
      image: require('../images/img07.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 4,
    },
    {
      id: 8,
      title: "Pistola CO2, Python, 6 tiros",
      price: 14500,
      image: require('../images/img08.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 3,
    },
    {
      id: 9,
      title: "Pistola CO2, Thunder, 19 tiros",
      price: 14500,
      image: require('../images/img09.jpg'),
      category: "Arma corta CO2",
      cantidad: 1,
      stock: 1,
    }, 
  ],
};

export default data;